services:
  db:
    image: mysql
    container_name: db-mytasks
    environment:
      MYSQL_ROOT_PASSWORD: mytasks123
      MYSQL_DATABASE: mytasks
    volumes:
      - vol-mytasks-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmytasks123"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: "./api"
    container_name: api-mytasks
    ports:
      - 8080:8080
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  frontend:
    build: "./frontend"
    container_name: front-mytasks
    ports:
      - 4200:4200
    depends_on:
      - db
      - api
    
volumes:
  vol-mytasks-db:
